apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lucas-store
  # This is an extra long description
  description: The lucastore is an example API used to show features of the OpenAPI spec.
  annotations:
    backstage.io/kubernetes-id: dice-roller
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - streetlights
    - hello-world
